### PR TITLE
Fix #9 issue, changing FileFacet class

### LINKED ISSUE #9: FileFacet class
- The following properties must be changed:
   - from uco-observable:fileLocalPath into drafting:fileLocalPath
   - from uco-core:objectCreatedTime into uco-observable:observableCreatedTime
   - from uco-core:objectModifiedTime into uco-observable:modifiedTime
   - from uco-core:objectAccessedTime into uco-observable:accessedTime 
- the uco-core:tag property must contain a string value and be put outside the core:hasFacet, because FileFacet is not a subclass of core:UcoObject. Alternatively it could be used the uco-observable:mimeType property.

### PR DESCRIPTION
**Pull request by fabrizio-turchi**
To be coherent should I define a type checking also for the dates? I left the code as it was by using the file_xxx_time=None as follows:

```python
def __init__(
        self,
        file_accessed_time=None,
        ...
        file_metadata_changed_time=None,
        file_modified_time=None,
        file_created_time=None,
    ):
```

### CODE REVIEW

**Comment by fabrizio-turchi** [comment]
Why did CI fail (again)? DO I have to better check my code to avoid the nuisance (to you)? Please let me know...

**Comment by ajnelson-nist** [comment]
It's no nuisance.

Logistics check: Are you able to see the CI logs seeing "Details" by the red X's?

You can reproduce the CI failures in your local environment by running `make check`.  There is a Makefile in this project that mimics what CI does.  You should be able to see that this is the same issue stemming from PEP 484 on the last PR.

**Comment by fabrizio-turchi** [comment]
Thanks! I'll try to fix the issue and push it again

**Review by ajnelson-nist — APPROVED** [review]
@fabrizio-turchi , I addressed a data issue in [`40a08c5`](https://github.com/casework/CASE-Mapping-Python/pull/49/commits/40a08c5794ed5e5d958ba3bb760d1ce7bf1f0d2f).  I'm leaving an Approve on this Pull Request, but because a substantial amount of code-design revision occurred in that patch, I'm going to leave it to you or @kchason to merge.  Please see that patch message for rationale.

**Pull request merged**
